// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYW0NfQ1XTyQoAQMVWlKSj393qSTBIGTg',
    appId: '1:487632279479:web:48494988b93df747e43a32',
    messagingSenderId: '487632279479',
    projectId: 'avecmoiwithus',
    authDomain: 'avecmoiwithus.firebaseapp.com',
    storageBucket: 'avecmoiwithus.appspot.com',
    measurementId: 'G-SK6D6R2EYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzhcxMUqNuvsaBVtlOUW-aRvD-L3N3SHk',
    appId: '1:487632279479:android:a048400ba2e21f11e43a32',
    messagingSenderId: '487632279479',
    projectId: 'avecmoiwithus',
    storageBucket: 'avecmoiwithus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0qhukztJIVxJA1_XjH4LmR5Oa9E38Of4',
    appId: '1:487632279479:ios:ed97e5188a1ad871e43a32',
    messagingSenderId: '487632279479',
    projectId: 'avecmoiwithus',
    storageBucket: 'avecmoiwithus.appspot.com',
    androidClientId: '487632279479-8rt61r6i3ofvc4ndedg46l4uj3glc3rg.apps.googleusercontent.com',
    iosClientId: '487632279479-sd6ec0vjofdd1m19ad5tn5jttjck2tb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.avecMoiWithUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0qhukztJIVxJA1_XjH4LmR5Oa9E38Of4',
    appId: '1:487632279479:ios:f91adf6790250d7de43a32',
    messagingSenderId: '487632279479',
    projectId: 'avecmoiwithus',
    storageBucket: 'avecmoiwithus.appspot.com',
    androidClientId: '487632279479-8rt61r6i3ofvc4ndedg46l4uj3glc3rg.apps.googleusercontent.com',
    iosClientId: '487632279479-l5do2cbqlhva2upqopkkg3gopvckhsvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.avecMoiWithUs.RunnerTests',
  );
}
